python3 gmos_extraction.py example/ExtractionCase1/extraction_config_1.yaml
python3 gmos_extraction.py example/ExtractionCase2/extraction_config_2.yaml
python3 gmos_extraction.py example/ExtractionCase3/extraction_config_3.yaml
python3 gmos_extraction.py example/ExtractionCase4/extraction_config_4.yaml
python3 gmos_extraction.py example/ExtractionCase5/extraction_config_5.yaml
python3 gmos_extraction.py example/ExtractionCase6/extraction_config_6.yaml
python3 gmos_extraction.py example/ExtractionCase7/extraction_config_7.yaml
